{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "go-mysql-api.serviceMonitorName" . }}
  labels:
    {{- include "go-mysql-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "go-mysql-api.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
