apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-mysql-api
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: go-mysql-api
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
        - name: ENVIRONMENT
          value: "dev"
        - name: DEBUG
          value: "true"
        - name: LOG_LEVEL
          value: "debug"
