name: Automated Security Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scans daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      security_scan_type:
        description: 'Type of security scan to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - vulnerability
          - compliance
          - policy
          - secrets

env:
  SECURITY_SCAN_VERSION: "v1.0.0"
  KUBERNETES_VERSION: "1.28"
  CAPI_VERSION: "v1.6.0"

jobs:
  # Automated Vulnerability Scanning
  vulnerability-scanning:
    name: Automated Vulnerability Scanning
    runs-on: ubuntu-latest
    if: github.event.inputs.security_scan_type == 'all' || github.event.inputs.security_scan_type == 'vulnerability' || github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH,MEDIUM'
        
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always() && hashFiles('trivy-results.sarif') != ''
      with:
        sarif_file: 'trivy-results.sarif'
        
    - name: Run Grype vulnerability scanner
      uses: anchore/grype-action@v1
      with:
        path: .
        output: 'sarif'
        output-file: 'grype-results.sarif'
        
    - name: Upload Grype scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always() && hashFiles('grype-results.sarif') != ''
      with:
        sarif_file: 'grype-results.sarif'
        
    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'terraforming-again'
        path: '.'
        format: 'SARIF'
        out: 'dependency-check-results.sarif'
        
    - name: Upload Dependency Check results
      uses: github/codeql-action/upload-sarif@v3
      if: always() && hashFiles('dependency-check-results.sarif') != ''
      with:
        sarif_file: 'dependency-check-results.sarif'

  # Automated Compliance Scanning
  compliance-scanning:
    name: Automated Compliance Scanning
    runs-on: ubuntu-latest
    if: github.event.inputs.security_scan_type == 'all' || github.event.inputs.security_scan_type == 'compliance'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run CIS Kubernetes Benchmark
      run: |
        # Install kube-bench
        curl -L https://github.com/aquasecurity/kube-bench/releases/latest/download/kube-bench_0.6.15_linux_amd64.tar.gz | tar xvz
        sudo mv kube-bench /usr/local/bin/
        
        # Run CIS benchmark for manifests
        kube-bench run --targets policies --config-dir=cfg --config=config.yaml --json > cis-results.json || true
        
    - name: Run Checkov for infrastructure compliance
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        framework: terraform,kubernetes,helm
        output_format: sarif
        output_file_path: checkov-compliance-results.sarif
        soft_fail: true
        
    - name: Upload Checkov compliance results
      uses: github/codeql-action/upload-sarif@v3
      if: always() && hashFiles('checkov-compliance-results.sarif') != ''
      with:
        sarif_file: checkov-compliance-results.sarif
        
    - name: Run Polaris for Kubernetes best practices
      run: |
        # Install Polaris
        curl -L https://github.com/FairwindsOps/polaris/releases/latest/download/polaris_linux_amd64.tar.gz | tar xvz
        sudo mv polaris /usr/local/bin/
        
        # Run Polaris on Kubernetes manifests
        find . -name "*.yaml" -path "*/kustomize/*" -o -path "*/templates/*" | while read file; do
          polaris audit --audit-path "$file" --format json > "polaris-$(basename "$file").json" || true
        done

  # Automated Policy Enforcement
  policy-enforcement:
    name: Automated Policy Enforcement
    runs-on: ubuntu-latest
    if: github.event.inputs.security_scan_type == 'all' || github.event.inputs.security_scan_type == 'policy'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run OPA Gatekeeper policies
      run: |
        # Install OPA
        curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
        chmod +x opa
        sudo mv opa /usr/local/bin/
        
        # Install Conftest
        curl -L https://github.com/open-policy-agent/conftest/releases/latest/download/conftest_0.45.0_Linux_x86_64.tar.gz | tar xz
        sudo mv conftest /usr/local/bin/
        
        # Run Conftest on Kubernetes manifests
        find . -name "*.yaml" -path "*/kustomize/*" -o -path "*/templates/*" | while read file; do
          conftest test "$file" --policy security/policies/ || true
        done
        
    - name: Run Kyverno policies
      run: |
        # Install Kyverno CLI
        curl -L https://github.com/kyverno/kyverno/releases/latest/download/kyverno-cli_v1.10.0_linux_x86_64.tar.gz | tar xz
        sudo mv kyverno /usr/local/bin/
        
        # Run Kyverno policy validation
        find . -name "*.yaml" -path "*/kustomize/*" -o -path "*/templates/*" | while read file; do
          kyverno apply "$file" --policy security/policies/kyverno/ || true
        done

  # Automated Secrets Detection
  secrets-detection:
    name: Automated Secrets Detection
    runs-on: ubuntu-latest
    if: github.event.inputs.security_scan_type == 'all' || github.event.inputs.security_scan_type == 'secrets'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Run TruffleHog for secrets detection
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD
        extra_args: --debug --only-verified
        
    - name: Run GitLeaks for secrets detection
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        
    - name: Run Semgrep for secrets detection
      uses: returntocorp/semgrep-action@v1
      with:
        config: >-
          p/secrets
          p/security-audit
        generateSarif: "1"
        sarifOutput: "semgrep-secrets.sarif"
        
    - name: Upload Semgrep secrets results
      uses: github/codeql-action/upload-sarif@v3
      if: always() && hashFiles('semgrep-secrets.sarif') != ''
      with:
        sarif_file: semgrep-secrets.sarif

  # Automated Security Remediation
  security-remediation:
    name: Automated Security Remediation
    runs-on: ubuntu-latest
    if: github.event.inputs.security_scan_type == 'all' || github.event_name == 'schedule'
    needs: [vulnerability-scanning, compliance-scanning, policy-enforcement, secrets-detection]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Auto-fix security issues
      run: |
        # Install security tools
        pip install safety bandit semgrep
        
        # Auto-fix Python security issues
        if [ -f "requirements.txt" ]; then
          safety check --json --output safety-report.json || true
          bandit -r . -f json -o bandit-report.json || true
        fi
        
        # Auto-fix Go security issues
        if [ -f "go.mod" ]; then
          go install github.com/securecodewarrior/gosec/v2/cmd/gosec@latest
          gosec -fmt json -out gosec-report.json ./... || true
        fi
        
    - name: Create security remediation PR
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'security: automated security remediation'
        title: 'Automated Security Remediation'
        body: |
          This PR contains automated security fixes:
          
          - Updated vulnerable dependencies
          - Fixed security policy violations
          - Remediated compliance issues
          - Removed exposed secrets
          
          **Security Scan Results:**
          - Vulnerability Scan: ${{ needs.vulnerability-scanning.result }}
          - Compliance Scan: ${{ needs.compliance-scanning.result }}
          - Policy Enforcement: ${{ needs.policy-enforcement.result }}
          - Secrets Detection: ${{ needs.secrets-detection.result }}
        branch: automated-security-remediation
        delete-branch: true

  # Security Dashboard
  security-dashboard:
    name: Security Dashboard
    runs-on: ubuntu-latest
    if: always()
    needs: [vulnerability-scanning, compliance-scanning, policy-enforcement, secrets-detection]
    
    steps:
    - name: Generate security dashboard
      run: |
        echo "## ðŸ”’ Security Dashboard" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Scan Date:** $(date)" >> $GITHUB_STEP_SUMMARY
        echo "**Repository:** ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
        echo "**Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ðŸ“Š Security Scan Results:" >> $GITHUB_STEP_SUMMARY
        echo "- **Vulnerability Scanning:** ${{ needs.vulnerability-scanning.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Compliance Scanning:** ${{ needs.compliance-scanning.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Policy Enforcement:** ${{ needs.policy-enforcement.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Secrets Detection:** ${{ needs.secrets-detection.result }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ðŸ›¡ï¸ Security Tools Used:" >> $GITHUB_STEP_SUMMARY
        echo "- Trivy (Vulnerability Scanner)" >> $GITHUB_STEP_SUMMARY
        echo "- Grype (Vulnerability Scanner)" >> $GITHUB_STEP_SUMMARY
        echo "- OWASP Dependency Check" >> $GITHUB_STEP_SUMMARY
        echo "- Checkov (Infrastructure Security)" >> $GITHUB_STEP_SUMMARY
        echo "- Polaris (Kubernetes Best Practices)" >> $GITHUB_STEP_SUMMARY
        echo "- OPA Gatekeeper (Policy Engine)" >> $GITHUB_STEP_SUMMARY
        echo "- Kyverno (Policy Engine)" >> $GITHUB_STEP_SUMMARY
        echo "- TruffleHog (Secrets Detection)" >> $GITHUB_STEP_SUMMARY
        echo "- GitLeaks (Secrets Detection)" >> $GITHUB_STEP_SUMMARY
        echo "- Semgrep (Code Security)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ðŸ”„ Next Steps:" >> $GITHUB_STEP_SUMMARY
        echo "- Review security scan results" >> $GITHUB_STEP_SUMMARY
        echo "- Address critical vulnerabilities" >> $GITHUB_STEP_SUMMARY
        echo "- Implement security policies" >> $GITHUB_STEP_SUMMARY
        echo "- Monitor compliance status" >> $GITHUB_STEP_SUMMARY
