#!/bin/bash
# Get Ansible Vault password from AWS SSM Parameter Store
# This script is generated by Terraform

set -euo pipefail

PARAMETER_NAME="${parameter_name}"
AWS_REGION="${aws_region}"

# Get the vault password from SSM Parameter Store
aws ssm get-parameter \
  --name "$PARAMETER_NAME" \
  --with-decryption \
  --region "$AWS_REGION" \
  --query 'Parameter.Value' \
  --output text
