# Ansible group_vars/all.yml - Non-sensitive variables
# This file is generated by Terraform

# Environment configuration
environment: "${environment}"

# Database configuration (non-sensitive)
db_host: "${db_host}"
db_port: "${db_port}"
db_name: "${db_name}"
db_user: "${db_user}"

# Application configuration
app_name: "go-mysql-api"
app_version: "latest"

# AWS configuration
aws_region: "us-west-2"

# Monitoring configuration
enable_monitoring: true
log_level: "info"

# Security configuration
enable_ssl: true
ssl_cert_path: "/etc/ssl/certs"
ssl_key_path: "/etc/ssl/private"
