# Ansible group_vars/vault.yml - Sensitive variables
# This file should be encrypted using: ansible-vault encrypt vault.yml
# This file is generated by Terraform

# Database credentials (sensitive)
rds_password: "foobar123"
rds_master_password: "foobar123"

# AWS Credentials (injected from Terraform)
aws_access_key_id: "${aws_access_key_id}"
aws_secret_access_key: "${aws_secret_access_key}"
aws_session_token: "${aws_session_token}"

# API keys and secrets
api_secret_key: "foobar_api_secret_key_123"
jwt_secret: "foobar_jwt_secret_123"
encryption_key: "foobar_encryption_key_123"

# External service credentials
github_token: "foobar_github_token_123"
docker_registry_password: "foobar_docker_password_123"

# SSL certificates (if stored as variables)
ssl_cert_content: "foobar_ssl_cert_content_123"
ssl_key_content: "foobar_ssl_key_content_123"

# Kubernetes secrets
kubernetes_token: "foobar_k8s_token_123"
etcd_ca_cert: "foobar_etcd_ca_cert_123"
etcd_client_cert: "foobar_etcd_client_cert_123"
etcd_client_key: "foobar_etcd_client_key_123"

# ELK Stack credentials
elasticsearch_password: "foobar_elasticsearch_password_123"
kibana_password: "foobar_kibana_password_123"
logstash_password: "foobar_logstash_password_123"
