apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-operator
  namespace: operators
  labels:
    app.kubernetes.io/name: ansible-operator
    app.kubernetes.io/part-of: operators
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ansible-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ansible-operator
        app.kubernetes.io/part-of: operators
    spec:
      serviceAccountName: ansible-operator
      containers:
      - name: ansible-operator
        image: ansible/ansible-runner:latest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: ANSIBLE_VAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ansible-vault-password
              key: password
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: operators-config
              key: AWS_REGION
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret-access-key
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: session-token
              optional: true
        - name: ANSIBLE_VERSION
          valueFrom:
            configMapKeyRef:
              name: operators-config
              key: ANSIBLE_VERSION
        - name: ANSIBLE_INVENTORY_PATH
          value: "/etc/ansible/inventory"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: ansible-inventory
          mountPath: /etc/ansible/inventory
          readOnly: true
      volumes:
      - name: ansible-inventory
        configMap:
          name: ansible-inventory
      imagePullSecrets:
      - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ansible-operator
  namespace: operators
  labels:
    app.kubernetes.io/name: ansible-operator
    app.kubernetes.io/part-of: operators
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: ansible-operator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ansible-inventory
  namespace: operators
  labels:
    app.kubernetes.io/name: ansible-operator
    app.kubernetes.io/part-of: operators
data:
  inventory.yml: |
    all:
      children:
        kubernetes_cluster:
          hosts:
            localhost:
              ansible_connection: local
              ansible_python_interpreter: python3
