apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: operators-base
  annotations:
    config.kubernetes.io/local-config: "true"

# Resources for operators
resources:
  - terraform-operator.yaml
  - vault-operator.yaml
  - ansible-operator.yaml
  - operators-namespace.yaml
  - operators-rbac.yaml

# Common labels
commonLabels:
  app.kubernetes.io/part-of: operators
  app.kubernetes.io/managed-by: kustomize

# Common annotations
commonAnnotations:
  kustomize.config.k8s.io/needs-hash-suffix: "true"

# Namespace
namespace: operators

# Images
images:
  - name: oamdev/terraform-controller
    newTag: v0.8.0
  - name: hashicorp/vault-operator
    newTag: latest
  - name: ansible/ansible-runner
    newTag: latest

# ConfigMap generator
configMapGenerator:
  - name: operators-config
    literals:
      - AWS_REGION=us-west-2
      - TERRAFORM_VERSION=1.5.0
      - VAULT_VERSION=latest
      - ANSIBLE_VERSION=latest
    options:
      disableNameSuffixHash: true

# Secret generator
secretGenerator:
  - name: aws-credentials
    literals:
      - access-key-id=foobar_access_key
      - secret-access-key=foobar_secret_key
      - session-token=foobar_session_token
    options:
      disableNameSuffixHash: true

  - name: ansible-vault-password
    literals:
      - password=foobar_vault_password
    options:
      disableNameSuffixHash: true

  - name: vault-token
    literals:
      - token=foobar_vault_token
    options:
      disableNameSuffixHash: true

# Patches for common configurations
patches:
  - path: terraform-operator-patch.yaml
    target:
      kind: Deployment
      name: terraform-operator
  - path: vault-operator-patch.yaml
    target:
      kind: Deployment
      name: vault-operator
  - path: ansible-operator-patch.yaml
    target:
      kind: Deployment
      name: ansible-operator

# Replicas
replicas:
  - name: terraform-operator
    count: 1
  - name: vault-operator
    count: 1
  - name: ansible-operator
    count: 1
