apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-operator
  namespace: operators
  labels:
    app.kubernetes.io/name: vault-operator
    app.kubernetes.io/part-of: operators
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault-operator
        app.kubernetes.io/part-of: operators
    spec:
      serviceAccountName: vault-operator
      containers:
      - name: vault-operator
        image: hashicorp/vault-operator:latest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: VAULT_ADDR
          value: "http://vault-server:8200"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
        - name: VAULT_VERSION
          valueFrom:
            configMapKeyRef:
              name: operators-config
              key: VAULT_VERSION
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      imagePullSecrets:
      - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: vault-operator
  namespace: operators
  labels:
    app.kubernetes.io/name: vault-operator
    app.kubernetes.io/part-of: operators
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: vault-operator
