apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodepools.karpenter.sh
  labels:
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/part-of: database-ci
spec:
  group: karpenter.sh
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              template:
                type: object
                properties:
                  metadata:
                    type: object
                    properties:
                      labels:
                        type: object
                        additionalProperties:
                          type: string
                      annotations:
                        type: object
                        additionalProperties:
                          type: string
                  spec:
                    type: object
                    properties:
                      requirements:
                        type: array
                        items:
                          type: object
                          properties:
                            key:
                              type: string
                            operator:
                              type: string
                              enum: ["In", "NotIn", "Exists", "DoesNotExist", "Gt", "Lt"]
                            values:
                              type: array
                              items:
                                type: string
                      resources:
                        type: object
                        properties:
                          requests:
                            type: object
                            additionalProperties:
                              type: string
                      taints:
                        type: array
                        items:
                          type: object
                          properties:
                            key:
                              type: string
                            value:
                              type: string
                            effect:
                              type: string
                              enum: ["NoSchedule", "PreferNoSchedule", "NoExecute"]
                      startupTaints:
                        type: array
                        items:
                          type: object
                          properties:
                            key:
                              type: string
                            value:
                              type: string
                            effect:
                              type: string
                              enum: ["NoSchedule", "PreferNoSchedule", "NoExecute"]
                      nodeClassRef:
                        type: object
                        properties:
                          apiVersion:
                            type: string
                          kind:
                            type: string
                          name:
                            type: string
                      machine:
                        type: object
                        properties:
                          type:
                            type: string
                          imageFamily:
                            type: string
                          imageSelector:
                            type: object
                            additionalProperties: true
                          instanceTypes:
                            type: array
                            items:
                              type: string
                          instanceStorePolicy:
                            type: string
                            enum: ["RAID0", "NVME"]
                          storage:
                            type: object
                            properties:
                              volumes:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                                    ebs:
                                      type: object
                                      properties:
                                        volumeType:
                                          type: string
                                        volumeSize:
                                          type: string
                                        iops:
                                          type: integer
                                        throughput:
                                          type: integer
                                        encrypted:
                                          type: boolean
                                        kmsKeyID:
                                          type: string
                                        deleteOnTermination:
                                          type: boolean
                                        snapshotID:
                                          type: string
                          detailedMonitoring:
                            type: boolean
                          metadataOptions:
                            type: object
                            properties:
                              httpEndpoint:
                                type: string
                                enum: ["enabled", "disabled"]
                              httpProtocolIPv6:
                                type: string
                                enum: ["enabled", "disabled"]
                              httpPutResponseHopLimit:
                                type: integer
                              httpTokens:
                                type: string
                                enum: ["optional", "required"]
                          blockDeviceMappings:
                            type: array
                            items:
                              type: object
                              properties:
                                deviceName:
                                  type: string
                                ebs:
                                  type: object
                                  properties:
                                    volumeType:
                                      type: string
                                    volumeSize:
                                      type: string
                                    iops:
                                      type: integer
                                    throughput:
                                      type: integer
                                    encrypted:
                                      type: boolean
                                    kmsKeyID:
                                      type: string
                                    deleteOnTermination:
                                      type: boolean
                                    snapshotID:
                                      type: string
                          userData:
                            type: string
                          amiSelector:
                            type: object
                            additionalProperties: true
                          amiFamily:
                            type: string
                          context:
                            type: string
                          role:
                            type: string
                          tags:
                            type: object
                            additionalProperties:
                              type: string
                          subnetSelector:
                            type: object
                            additionalProperties: true
                          securityGroupSelector:
                            type: object
                            additionalProperties: true
                      scheduling:
                        type: object
                        properties:
                          nodeSelector:
                            type: object
                            additionalProperties:
                              type: string
                          affinity:
                            type: object
                            properties:
                              nodeAffinity:
                                type: object
                                properties:
                                  requiredDuringSchedulingIgnoredDuringExecution:
                                    type: object
                                    properties:
                                      nodeSelectorTerms:
                                        type: array
                                        items:
                                          type: object
                                          properties:
                                            matchExpressions:
                                              type: array
                                              items:
                                                type: object
                                                properties:
                                                  key:
                                                    type: string
                                                  operator:
                                                    type: string
                                                    enum: ["In", "NotIn", "Exists", "DoesNotExist", "Gt", "Lt"]
                                                  values:
                                                    type: array
                                                    items:
                                                      type: string
                                            matchFields:
                                              type: array
                                              items:
                                                type: object
                                                properties:
                                                  key:
                                                    type: string
                                                  operator:
                                                    type: string
                                                    enum: ["In", "NotIn", "Exists", "DoesNotExist", "Gt", "Lt"]
                                                  values:
                                                    type: array
                                                    items:
                                                      type: string
                                  preferredDuringSchedulingIgnoredDuringExecution:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        weight:
                                          type: integer
                                        preference:
                                          type: object
                                          properties:
                                            matchExpressions:
                                              type: array
                                              items:
                                                type: object
                                                properties:
                                                  key:
                                                    type: string
                                                  operator:
                                                    type: string
                                                    enum: ["In", "NotIn", "Exists", "DoesNotExist", "Gt", "Lt"]
                                                  values:
                                                    type: array
                                                    items:
                                                      type: string
                                            matchFields:
                                              type: array
                                              items:
                                                type: object
                                                properties:
                                                  key:
                                                    type: string
                                                  operator:
                                                    type: string
                                                    enum: ["In", "NotIn", "Exists", "DoesNotExist", "Gt", "Lt"]
                                                  values:
                                                    type: array
                                                    items:
                                                      type: string
                              podAffinity:
                                type: object
                              podAntiAffinity:
                                type: object
                          tolerations:
                            type: array
                            items:
                              type: object
                              properties:
                                key:
                                  type: string
                                operator:
                                  type: string
                                  enum: ["Equal", "Exists"]
                                value:
                                  type: string
                                effect:
                                  type: string
                                  enum: ["NoSchedule", "PreferNoSchedule", "NoExecute"]
                                tolerationSeconds:
                                  type: integer
              limits:
                type: object
                properties:
                  cpu:
                    type: string
                  memory:
                    type: string
              disruption:
                type: object
                properties:
                  consolidateAfter:
                    type: string
                  consolidateUnder:
                    type: string
                  expireAfter:
                    type: string
                  budgets:
                    type: array
                    items:
                      type: object
                      properties:
                        nodes:
                          type: string
                        duration:
                          type: string
                        events:
                          type: object
                          additionalProperties:
                            type: string
              weight:
                type: integer
                minimum: 1
                maximum: 100
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
              nodes:
                type: object
                properties:
                  ready:
                    type: string
                  notReady:
                    type: string
              resources:
                type: object
                properties:
                  cpu:
                    type: object
                    properties:
                      requests:
                        type: string
                      limits:
                        type: string
                      capacity:
                        type: string
                  memory:
                    type: object
                    properties:
                      requests:
                        type: string
                      limits:
                        type: string
                      capacity:
                        type: string
    subresources:
      status: {}
  scope: Cluster
  names:
    plural: nodepools
    singular: nodepool
    kind: NodePool
    shortNames:
    - np
