apiVersion: v1
kind: Service
metadata:
  name: go-mysql-api
  labels:
    app.kubernetes.io/name: go-mysql-api
    app.kubernetes.io/part-of: database-ci
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app.kubernetes.io/name: go-mysql-api
