{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "go-mysql-api.networkPolicyName" . }}
  labels:
    {{- include "go-mysql-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "go-mysql-api.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- end }}
{{- end }}
