apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ansiblejobs.ansible.io
  labels:
    app.kubernetes.io/name: ansible-operator
    app.kubernetes.io/part-of: database-ci
spec:
  group: ansible.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              ansible:
                type: object
                properties:
                  version:
                    type: string
                    default: "2.15.0"
                  inventory:
                    type: object
                    properties:
                      type:
                        type: string
                        enum: ["static", "dynamic", "file"]
                        default: "static"
                      hosts:
                        type: array
                        items:
                          type: string
                      inventoryFile:
                        type: string
                      dynamicInventory:
                        type: object
                        properties:
                          script:
                            type: string
                          config:
                            type: object
                            additionalProperties: true
                  playbook:
                    type: object
                    properties:
                      path:
                        type: string
                      name:
                        type: string
                      extraVars:
                        type: object
                        additionalProperties: true
                      tags:
                        type: array
                        items:
                          type: string
                      skipTags:
                        type: array
                        items:
                          type: string
                      limit:
                        type: string
                      checkMode:
                        type: boolean
                        default: false
                      diffMode:
                        type: boolean
                        default: false
                  vault:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: true
                      passwordPath:
                        type: string
                        default: "/ansible/vault/password"
                      vaultFiles:
                        type: array
                        items:
                          type: string
              git:
                type: object
                properties:
                  repository:
                    type: string
                  branch:
                    type: string
                    default: "main"
                  path:
                    type: string
                    default: "ansible/"
                  credentials:
                    type: object
                    properties:
                      secretName:
                        type: string
                      secretKey:
                        type: string
              aws:
                type: object
                properties:
                  region:
                    type: string
                  credentials:
                    type: object
                    properties:
                      secretName:
                        type: string
                      secretKey:
                        type: string
                  ssm:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: true
                      parameterStore:
                        type: object
                        additionalProperties: true
              environment:
                type: string
                default: "dev"
              logLevel:
                type: string
                enum: ["debug", "info", "warn", "error"]
                default: "info"
              debug:
                type: boolean
                default: false
              retryPolicy:
                type: object
                properties:
                  maxRetries:
                    type: integer
                    default: 3
                  backoffDuration:
                    type: string
                    default: "30s"
              timeout:
                type: string
                default: "30m"
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Running", "Succeeded", "Failed", "Cancelled"]
              lastExecuted:
                type: string
                format: date-time
              lastError:
                type: string
              ansibleVersion:
                type: string
              playbookResults:
                type: object
                properties:
                  changed:
                    type: integer
                  failed:
                    type: integer
                  ok:
                    type: integer
                  skipped:
                    type: integer
                  unreachable:
                    type: integer
              executionTime:
                type: string
              retryCount:
                type: integer
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: ansiblejobs
    singular: ansiblejob
    kind: AnsibleJob
    shortNames:
    - aj
    - ansible
