{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-mysql-api.fullname" . }}-secrets-{{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum | trunc 8 }}
  labels:
    {{- include "go-mysql-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret.data }}
  {{- toYaml .Values.secret.data | nindent 2 }}
  {{- end }}
  # Database password (base64 encoded)
  db_password: {{ .Values.env.DB_PASSWORD | default "U2VjdXJlUGFzc3dvcmQxMjMh" | b64enc }}
{{- end }}
