apiVersion: vault.io/v1alpha1
kind: VaultSecret
metadata:
  name: database-secrets
  namespace: operators
  labels:
    app.kubernetes.io/name: database-secrets
    app.kubernetes.io/part-of: database-ci
    app.kubernetes.io/component: vault
spec:
  vault:
    address: "https://internal.coderedalarmtech.com/vault"
    namespace: "vault"
    authMethod: "kubernetes"
    tokenPath: "/vault/operator/token"
    awsAuth:
      enabled: false
      role: "vault-operator-role"
      region: "us-east-1"
  ssm:
    enabled: true
    region: "us-east-1"
    parameterStore:
      vaultToken: "/vault/operator/token"
      vaultConfig: "/vault/operator/config"
      awsCredentials: "/vault/operator/aws-credentials"
      ansibleVaultPassword: "/ansible/vault/password"
      customSecrets:
        - path: "/app/database/password"
          key: "db_password"
        - path: "/app/api/keys"
          key: "api_key"
    parameterStoreConfig:
      refreshInterval: "5m"
      withDecryption: true
      filters:
        - name: "tag:Environment"
          values: ["dev", "test", "sandbox"]
  aws:
    region: "us-east-1"
    credentials:
      secretName: "vault-operator-aws-credentials"
      secretKey: "credentials"
    iamRole: "arn:aws:iam::123456789012:role/VaultOperatorSSMRole"
  git:
    repository: "https://github.com/blind3dd/database_CI.git"
    branch: "main"
    path: "vault/policies/"
    credentials:
      secretName: "vault-git-credentials"
      secretKey: "credentials"
  environment: "dev"
  logLevel: "info"
  debug: false
  features:
    secretRotation: true
    secretSync: true
    auditLogging: true
    metrics: true
  secrets:
    - name: "database-credentials"
      path: "secret/data/go-mysql-api/database"
      keys: ["username", "password", "host", "port"]
      targetSecret: "database-secrets"
      targetNamespace: "go-mysql-api"
    - name: "api-keys"
      path: "secret/data/go-mysql-api/app"
      keys: ["api_key", "jwt_secret"]
      targetSecret: "api-secrets"
      targetNamespace: "go-mysql-api"
    - name: "aws-credentials"
      path: "secret/data/go-mysql-api/aws"
      keys: ["access_key", "secret_key", "region"]
      targetSecret: "aws-secrets"
      targetNamespace: "go-mysql-api"
