apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter
  namespace: karpenter
  labels:
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/part-of: autoscaling
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: karpenter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: karpenter
        app.kubernetes.io/part-of: autoscaling
    spec:
      serviceAccountName: karpenter
      containers:
      - name: karpenter
        image: public.ecr.aws/karpenter/karpenter:v0.37.0
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: AWS_DEFAULT_REGION
          value: "us-west-2"
        - name: CLUSTER_NAME
          value: "kubernetes-cluster"
        - name: INTERRUPTION_QUEUE
          value: "interruption-queue"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
