apiVersion: v1
kind: Service
metadata:
  name: karpenter
  namespace: karpenter
  labels:
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/part-of: autoscaling
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: webhook
    port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/part-of: autoscaling
