---
# Consolidated Ansible Galaxy collections (single YAML document)
collections:
  - name: kubernetes.core
    version: ">=2.4.0"
  - name: amazon.aws
    version: ">=6.0.0"
  - name: community.general
    version: ">=7.0.0"
  - name: ansible.windows
    version: ">=1.0.0"
