apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-mysql-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      containers:
      - name: go-mysql-api
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
        - name: ENVIRONMENT
          value: "dev"
        - name: LOG_LEVEL
          value: "debug"
