apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: go-mysql-api-base
  annotations:
    config.kubernetes.io/local-config: "true"

# Resources from the existing Helm chart templates
resources:
  - ../../go-mysql-api/chart/templates/deployment.yaml
  - ../../go-mysql-api/chart/templates/service.yaml
  - ../../go-mysql-api/chart/templates/configmap.yaml
  - ../../go-mysql-api/chart/templates/secret.yaml
  - ../../go-mysql-api/chart/templates/serviceaccount.yaml
  - ../../go-mysql-api/chart/templates/networkpolicy.yaml
  - ../../go-mysql-api/chart/templates/ingress.yaml
  - ../../go-mysql-api/chart/templates/hpa.yaml
  - ../../go-mysql-api/chart/templates/pdb.yaml
  - ../../go-mysql-api/chart/templates/servicemonitor.yaml

# Istio resources
  - ../../go-mysql-api/chart/templates/gateway.yaml
  - ../../go-mysql-api/chart/templates/virtualservice.yaml
  - ../../go-mysql-api/chart/templates/destinationrule.yaml
  - ../../go-mysql-api/chart/templates/authorizationpolicy.yaml
  - ../../go-mysql-api/chart/templates/peerauthentication.yaml

# Vault integration
  - ../../go-mysql-api/chart/templates/vault-config.yaml
  - ../../go-mysql-api/chart/templates/vault-deployment.yaml
  - ../../go-mysql-api/chart/templates/vault-service.yaml
  - ../../go-mysql-api/chart/templates/vault-serviceaccount.yaml

# Common labels
commonLabels:
  app.kubernetes.io/name: go-mysql-api
  app.kubernetes.io/part-of: database-ci
  app.kubernetes.io/managed-by: kustomize

# Common annotations
commonAnnotations:
  kustomize.config.k8s.io/needs-hash-suffix: "true"

# Namespace
namespace: go-mysql-api

# Images
images:
  - name: go-mysql-api
    newTag: latest

# ConfigMap generator
configMapGenerator:
  - name: go-mysql-api-config
    literals:
      - APP_NAME=go-mysql-api
      - LOG_LEVEL=info
      - SERVER_PORT=8080
      - HEALTH_CHECK_PATH=/health
      - METRICS_PATH=/metrics
    options:
      disableNameSuffixHash: true

# Secret generator
secretGenerator:
  - name: go-mysql-api-secrets
    literals:
      - DB_HOST=mysql-service
      - DB_PORT=3306
      - DB_NAME=go_mysql_api
      - DB_USER=api_user
      - DB_PASSWORD=changeme
    options:
      disableNameSuffixHash: true

# Patches for common configurations
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: go-mysql-api
  - path: service-patch.yaml
    target:
      kind: Service
      name: go-mysql-api

# Replicas
replicas:
  - name: go-mysql-api
    count: 2
