apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

commonLabels:
  environment: dev

patches:
  - path: replicas-patch.yaml
  - path: service-patch.yaml

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - ENVIRONMENT=dev
      - LOG_LEVEL=debug
      # DB values will be updated by Ansible from Terraform outputs
      - DB_HOST=changeme  # Replaced by Ansible
      - DB_NAME=mock_user

