{{- if .Values.imagePullSecrets }}
{{- range .Values.imagePullSecrets }}
{{- if .create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- include "go-mysql-api.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"AWS\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .registry .password .email .auth | b64enc }}
{{- end }}
{{- end }}
{{- end }}
