---
# Default variables for Kubernetes Operators role

# Namespace configuration
k8s_operators_namespace: "operators"

# Terraform Operator configuration
install_terraform_operator: true
terraform_operator_replicas: 1
terraform_operator_image_repository: "oamdev/terraform-controller"
terraform_operator_image_tag: "v0.8.0"
terraform_operator_image_pull_policy: "IfNotPresent"
terraform_operator_cpu_request: "100m"
terraform_operator_memory_request: "256Mi"
terraform_operator_cpu_limit: "500m"
terraform_operator_memory_limit: "512Mi"

# HashiCorp Vault Operator configuration
install_vault_operator: true
vault_operator_replicas: 1
vault_operator_image_repository: "hashicorp/vault-operator"
vault_operator_image_tag: "latest"
vault_operator_image_pull_policy: "IfNotPresent"
vault_operator_cpu_request: "100m"
vault_operator_memory_request: "256Mi"
vault_operator_cpu_limit: "500m"
vault_operator_memory_limit: "512Mi"

# Vault Server configuration (if installing with operator)
install_vault_server: false
vault_server_replicas: 1
vault_server_image_repository: "hashicorp/vault"
vault_server_image_tag: "latest"
vault_server_cpu_request: "100m"
vault_server_memory_request: "256Mi"
vault_server_cpu_limit: "500m"
vault_server_memory_limit: "512Mi"

# Ansible Operator configuration
install_ansible_operator: true
ansible_operator_replicas: 1
ansible_operator_image_repository: "ansible/ansible-runner"
ansible_operator_image_tag: "latest"
ansible_operator_image_pull_policy: "IfNotPresent"
ansible_operator_cpu_request: "100m"
ansible_operator_memory_request: "256Mi"
ansible_operator_cpu_limit: "500m"
ansible_operator_memory_limit: "512Mi"

# Ansible configuration
ansible_inventory_path: "/etc/ansible/inventory"
ansible_vault_password: "{{ vault.ansible_vault_password | default('changeme') }}"

# Helm configuration
helm_timeout: 300
helm_wait: true
helm_wait_for_jobs: true
