{{- if .Values.vault.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "go-mysql-api.fullname" . }}-vault
  labels:
    {{- include "go-mysql-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: vault
{{- end }}
