apiVersion: ansible.io/v1alpha1
kind: AnsibleJob
metadata:
  name: database-deployment
  namespace: operators
  labels:
    app.kubernetes.io/name: database-deployment
    app.kubernetes.io/part-of: database-ci
    app.kubernetes.io/component: ansible
spec:
  ansible:
    version: "2.15.0"
    inventory:
      type: "static"
      hosts:
        - "control-plane-1"
        - "control-plane-2"
        - "control-plane-3"
        - "worker-1"
        - "worker-2"
        - "worker-3"
    playbook:
      path: "ansible/playbooks/kubernetes-istio.yml"
      name: "kubernetes-istio.yml"
      extraVars:
        environment: "dev"
        region: "us-east-1"
        cluster_name: "database-ci-cluster"
      tags:
        - "kubernetes"
        - "istio"
      skipTags:
        - "debug"
      limit: "all"
      checkMode: false
      diffMode: false
    vault:
      enabled: true
      passwordPath: "/ansible/vault/password"
      vaultFiles:
        - "ansible/group_vars/vault.yml"
  git:
    repository: "https://github.com/blind3dd/database_CI.git"
    branch: "main"
    path: "ansible/"
    credentials:
      secretName: "ansible-git-credentials"
      secretKey: "credentials"
  aws:
    region: "us-east-1"
    credentials:
      secretName: "ansible-aws-credentials"
      secretKey: "credentials"
    ssm:
      enabled: true
      parameterStore:
        ansible_vault_password: "/ansible/vault/password"
        aws_credentials: "/ansible/aws/credentials"
        terraform_outputs: "/terraform/outputs"
  environment: "dev"
  logLevel: "info"
  debug: false
  retryPolicy:
    maxRetries: 3
    backoffDuration: "30s"
  timeout: "30m"
