apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: terraformconfigs.terraform.io
  labels:
    app.kubernetes.io/name: terraform-operator
    app.kubernetes.io/part-of: database-ci
spec:
  group: terraform.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              terraform:
                type: object
                properties:
                  version:
                    type: string
                    default: "1.6.0"
                  backend:
                    type: object
                    properties:
                      type:
                        type: string
                        enum: ["s3", "gcs", "azurerm", "local"]
                      bucket:
                        type: string
                      region:
                        type: string
                      key:
                        type: string
                  workspace:
                    type: string
                    default: "default"
              git:
                type: object
                properties:
                  repository:
                    type: string
                  branch:
                    type: string
                    default: "main"
                  path:
                    type: string
                    default: "."
                  credentials:
                    type: object
                    properties:
                      secretName:
                        type: string
                      secretKey:
                        type: string
              aws:
                type: object
                properties:
                  region:
                    type: string
                  credentials:
                    type: object
                    properties:
                      secretName:
                        type: string
                      secretKey:
                        type: string
              environment:
                type: string
                default: "dev"
              logLevel:
                type: string
                enum: ["debug", "info", "warn", "error"]
                default: "info"
              debug:
                type: boolean
                default: false
              variables:
                type: object
                additionalProperties: true
              autoApply:
                type: boolean
                default: false
              retryPolicy:
                type: object
                properties:
                  maxRetries:
                    type: integer
                    default: 3
                  backoffDuration:
                    type: string
                    default: "30s"
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Running", "Succeeded", "Failed"]
              lastApplied:
                type: string
                format: date-time
              lastError:
                type: string
              terraformVersion:
                type: string
              workspace:
                type: string
              resources:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    name:
                      type: string
                    status:
                      type: string
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: terraformconfigs
    singular: terraformconfig
    kind: TerraformConfig
    shortNames:
    - tfconfig
    - tf
