apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-workflow
  namespace: argocd
  labels:
    app.kubernetes.io/name: gitops-workflow
    app.kubernetes.io/part-of: database-ci
    app.kubernetes.io/component: workflow
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: CreateNamespace=true
    argocd.argoproj.io/sync-options: PrunePropagationPolicy=foreground
    argocd.argoproj.io/sync-options: PruneLast=true
spec:
  project: database-ci-project
  
  source:
    repoURL: https://github.com/blind3dd/database_CI.git
    targetRevision: HEAD
    path: argocd/applications
    directory:
      recurse: true
      include: "*.yaml"
      exclude: "gitops-workflow.yaml"
    
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    
  revisionHistoryLimit: 10

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: database-ci
    app.kubernetes.io/component: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: CreateNamespace=true
    argocd.argoproj.io/sync-options: PrunePropagationPolicy=foreground
    argocd.argoproj.io/sync-options: PruneLast=true
spec:
  project: database-ci-project
  
  source:
    repoURL: https://github.com/blind3dd/database_CI.git
    targetRevision: HEAD
    path: kustomize/monitoring/base
    kustomize:
      commonLabels:
        app.kubernetes.io/name: monitoring
        app.kubernetes.io/part-of: database-ci
        app.kubernetes.io/component: monitoring
        app.kubernetes.io/managed-by: argocd
      commonAnnotations:
        argocd.argoproj.io/sync-wave: "1"
        deployment.kubernetes.io/revision: ${{ github.run_number }}
    
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    
  revisionHistoryLimit: 10
  
  # Health checks
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: prometheus
    namespace: monitoring
  - apiVersion: apps/v1
    kind: Deployment
    name: grafana
    namespace: monitoring
  - apiVersion: apps/v1
    kind: Deployment
    name: alertmanager
    namespace: monitoring

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-system
  namespace: argocd
  labels:
    app.kubernetes.io/name: istio
    app.kubernetes.io/part-of: database-ci
    app.kubernetes.io/component: service-mesh
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: CreateNamespace=true
    argocd.argoproj.io/sync-options: PrunePropagationPolicy=foreground
    argocd.argoproj.io/sync-options: PruneLast=true
spec:
  project: database-ci-project
  
  source:
    repoURL: https://github.com/blind3dd/database_CI.git
    targetRevision: HEAD
    path: kustomize/istio/base
    kustomize:
      commonLabels:
        app.kubernetes.io/name: istio
        app.kubernetes.io/part-of: database-ci
        app.kubernetes.io/component: service-mesh
        app.kubernetes.io/managed-by: argocd
      commonAnnotations:
        argocd.argoproj.io/sync-wave: "1"
        deployment.kubernetes.io/revision: ${{ github.run_number }}
    
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    
  revisionHistoryLimit: 10
  
  # Health checks
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: istiod
    namespace: istio-system
  - apiVersion: apps/v1
    kind: Deployment
    name: istio-ingressgateway
    namespace: istio-system
  - apiVersion: apps/v1
    kind: Deployment
    name: istio-egressgateway
    namespace: istio-system

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-operator
  namespace: argocd
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: database-ci
    app.kubernetes.io/component: secrets-management
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: CreateNamespace=true
    argocd.argoproj.io/sync-options: PrunePropagationPolicy=foreground
    argocd.argoproj.io/sync-options: PruneLast=true
spec:
  project: database-ci-project
  
  source:
    repoURL: https://github.com/blind3dd/database_CI.git
    targetRevision: HEAD
    path: kustomize/operators/vault-operator
    kustomize:
      commonLabels:
        app.kubernetes.io/name: vault
        app.kubernetes.io/part-of: database-ci
        app.kubernetes.io/component: secrets-management
        app.kubernetes.io/managed-by: argocd
      commonAnnotations:
        argocd.argoproj.io/sync-wave: "1"
        deployment.kubernetes.io/revision: ${{ github.run_number }}
    
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    
  revisionHistoryLimit: 10
  
  # Health checks
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: vault-operator
    namespace: vault
  - apiVersion: v1
    kind: Service
    name: vault
    namespace: vault

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
  labels:
    app.kubernetes.io/name: cluster-autoscaler
    app.kubernetes.io/part-of: database-ci
    app.kubernetes.io/component: autoscaling
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: CreateNamespace=true
    argocd.argoproj.io/sync-options: PrunePropagationPolicy=foreground
    argocd.argoproj.io/sync-options: PruneLast=true
spec:
  project: database-ci-project
  
  source:
    repoURL: https://github.com/blind3dd/database_CI.git
    targetRevision: HEAD
    path: kustomize/cluster-autoscaler/overlays/${{ env.ENVIRONMENT || 'dev' }}
    kustomize:
      commonLabels:
        app.kubernetes.io/name: cluster-autoscaler
        app.kubernetes.io/part-of: database-ci
        app.kubernetes.io/component: autoscaling
        app.kubernetes.io/managed-by: argocd
      commonAnnotations:
        argocd.argoproj.io/sync-wave: "1"
        deployment.kubernetes.io/revision: ${{ github.run_number }}
    
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    
  revisionHistoryLimit: 10
  
  # Health checks
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: cluster-autoscaler
    namespace: kube-system

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  labels:
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/part-of: database-ci
    app.kubernetes.io/component: autoscaling
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: CreateNamespace=true
    argocd.argoproj.io/sync-options: PrunePropagationPolicy=foreground
    argocd.argoproj.io/sync-options: PruneLast=true
spec:
  project: database-ci-project
  
  source:
    repoURL: https://github.com/blind3dd/database_CI.git
    targetRevision: HEAD
    path: kustomize/karpenter/overlays/${{ env.ENVIRONMENT || 'dev' }}
    kustomize:
      commonLabels:
        app.kubernetes.io/name: karpenter
        app.kubernetes.io/part-of: database-ci
        app.kubernetes.io/component: autoscaling
        app.kubernetes.io/managed-by: argocd
      commonAnnotations:
        argocd.argoproj.io/sync-wave: "1"
        deployment.kubernetes.io/revision: ${{ github.run_number }}
    
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    
  revisionHistoryLimit: 10
  
  # Health checks
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: karpenter
    namespace: karpenter
  - apiVersion: v1
    kind: Service
    name: karpenter
    namespace: karpenter

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operators
  namespace: argocd
  labels:
    app.kubernetes.io/name: operators
    app.kubernetes.io/part-of: database-ci
    app.kubernetes.io/component: operators
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: CreateNamespace=true
    argocd.argoproj.io/sync-options: PrunePropagationPolicy=foreground
    argocd.argoproj.io/sync-options: PruneLast=true
spec:
  project: database-ci-project
  
  source:
    repoURL: https://github.com/blind3dd/database_CI.git
    targetRevision: HEAD
    path: kustomize/operators/overlays/${{ env.ENVIRONMENT || 'dev' }}
    kustomize:
      commonLabels:
        app.kubernetes.io/name: operators
        app.kubernetes.io/part-of: database-ci
        app.kubernetes.io/component: operators
        app.kubernetes.io/managed-by: argocd
      commonAnnotations:
        argocd.argoproj.io/sync-wave: "1"
        deployment.kubernetes.io/revision: ${{ github.run_number }}
    
  destination:
    server: https://kubernetes.default.svc
    namespace: operators
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    
  revisionHistoryLimit: 10
  
  # Health checks
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: ansible-operator
    namespace: operators
  - apiVersion: apps/v1
    kind: Deployment
    name: terraform-operator
    namespace: operators
  - apiVersion: v1
    kind: Service
    name: ansible-operator
    namespace: operators
  - apiVersion: v1
    kind: Service
    name: terraform-operator
    namespace: operators

