#cloud-config
# Kubernetes Worker Node CloudInit Configuration
# This configures the base system for Kubernetes worker nodes

users:
  - name: ec2-user
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}

# Package installation
packages:
  - docker
  - containerd
  - curl
  - wget
  - git
  - jq
  - yum-utils
  - device-mapper-persistent-data
  - lvm2
  - amazon-cloudwatch-agent
  - cowsay
  - fortune-mod

# Package repositories
package_update: true
package_upgrade: true

# Write files
write_files:
  - path: /etc/hosts
    content: |
      127.0.0.1 localhost
      ::1 localhost ip6-localhost ip6-loopback
      fe00::0 ip6-localnet
      ff00::0 ip6-mcastprefix
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters

  - path: /etc/sysctl.d/99-kubernetes-cri.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
      vm.swappiness                       = 0

  - path: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter

  - path: /etc/containerd/config.toml
    content: |
      version = 2
      root = "/var/lib/containerd"
      state = "/run/containerd"
      
      [grpc]
        address = "/run/containerd/containerd.sock"
        uid = 0
        gid = 0
      
      [plugins]
        [plugins."io.containerd.grpc.v1.cri"]
          sandbox_image = "registry.k8s.io/pause:3.9"
          stream_server_address = "127.0.0.1"
          stream_server_port = "0"
          enable_selinux = false
          enable_tls_streaming = false
          max_container_log_line_size = 16384
          
          [plugins."io.containerd.grpc.v1.cri".containerd]
            snapshotter = "overlayfs"
            default_runtime_name = "runc"
            no_pivot = false
            
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                runtime_type = "io.containerd.runc.v2"
                
                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
                  SystemdCgroup = true

  - path: /etc/docker/daemon.json
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2",
        "storage-opts": [
          "overlay2.override_kernel_check=true"
        ]
      }

  - path: /etc/systemd/system/docker.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd

  - path: /home/ec2-user/.bashrc
    content: |
      # .bashrc
      
      # Source global definitions
      if [ -f /etc/bashrc ]; then
        . /etc/bashrc
      fi
      
      # User specific environment
      PATH="$HOME/.local/bin:$HOME/bin:$PATH"
      export PATH
      
      # Kubernetes aliases
      alias k='kubectl'
      alias kg='kubectl get'
      alias kd='kubectl describe'
      alias kl='kubectl logs'
      alias ke='kubectl exec -it'
      
      # Fun welcome message
      if [ -x /usr/games/fortune ]; then
        echo "🐳 Welcome to Kubernetes Worker Node! 🐳"
        /usr/games/fortune | /usr/games/cowsay
        echo ""
        echo "📊 Node Info:"
        echo "   Environment: ${environment}"
        echo "   Service: ${service_name}"
        echo "   Cluster: ${cluster_name}"
        echo "   Pod CIDR: ${pod_cidr}"
        echo "   Service CIDR: ${service_cidr}"
        echo ""
        echo "🔧 Available commands:"
        echo "   k, kg, kd, kl, ke - kubectl shortcuts"
        echo "   sudo systemctl status kubelet - Check kubelet status"
        echo "   sudo journalctl -u kubelet -f - View kubelet logs"
        echo ""
      fi

# Run commands
runcmd:
  # Load kernel modules
  - modprobe overlay
  - modprobe br_netfilter
  
  # Apply sysctl settings
  - sysctl --system
  
  # Start and enable services
  - systemctl daemon-reload
  - systemctl enable containerd
  - systemctl start containerd
  - systemctl enable docker
  - systemctl start docker
  
  # Create directories
  - mkdir -p /var/log/calico/cni
  - mkdir -p /opt/cni/bin
  - mkdir -p /var/lib/kubelet
  - mkdir -p /var/lib/kube-proxy
  - mkdir -p /var/lib/kubernetes
  - mkdir -p /var/run/kubernetes
  
  # Set permissions
  - chown -R ec2-user:ec2-user /home/ec2-user/.bashrc
  
  # Install AWS CLI v2
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - ./aws/install
  - rm -rf aws awscliv2.zip
  
  # Configure AWS CLI for IMDSv2
  - aws configure set default.region ${aws_region}
  - aws configure set default.imds_use_http_tokens required
  
  # Install kubectl
  - curl -LO "https://dl.k8s.io/release/v${kubernetes_version}/bin/linux/amd64/kubectl"
  - chmod +x kubectl
  - mv kubectl /usr/local/bin/
  
  # Install kubeadm
  - curl -LO "https://dl.k8s.io/release/v${kubernetes_version}/bin/linux/amd64/kubeadm"
  - chmod +x kubeadm
  - mv kubeadm /usr/local/bin/
  
  # Install kubelet
  - curl -LO "https://dl.k8s.io/release/v${kubernetes_version}/bin/linux/amd64/kubelet"
  - chmod +x kubelet
  - mv kubelet /usr/local/bin/
  
  # Download kubelet systemd service
  - curl -LO "https://raw.githubusercontent.com/kubernetes/release/master/cmd/kubepkg/templates/latest/deb/kubelet/lib/systemd/system/kubelet.service"
  - mv kubelet.service /etc/systemd/system/
  
  # Download kubelet configuration
  - curl -LO "https://raw.githubusercontent.com/kubernetes/release/master/cmd/kubepkg/templates/latest/deb/kubelet/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
  - mkdir -p /etc/systemd/system/kubelet.service.d
  - mv 10-kubeadm.conf /etc/systemd/system/kubelet.service.d/
  
  # Enable and start kubelet
  - systemctl daemon-reload
  - systemctl enable kubelet
  
  # Create kubelet configuration
  - mkdir -p /var/lib/kubelet
  - cat > /var/lib/kubelet/config.yaml <<EOF
      apiVersion: kubelet.config.k8s.io/v1beta1
      kind: KubeletConfiguration
      cgroupDriver: systemd
      containerRuntimeEndpoint: unix:///run/containerd/containerd.sock
      runtimeRequestTimeout: "15m"
      failSwapOn: false
      authentication:
        anonymous:
          enabled: false
        webhook:
          enabled: true
        x509:
          clientCAFile: "/etc/kubernetes/pki/ca.crt"
      authorization:
        mode: Webhook
      clusterDomain: "cluster.local"
      clusterDNS:
      - "172.17.0.10"
      runtimeCgroups: "/system.slice/containerd.service"
      cgroupRoot: "/"
      cgroupsPerQOS: true
      cgroupDriver: systemd
      containerRuntimeEndpoint: unix:///run/containerd/containerd.sock
      runtimeRequestTimeout: "15m"
      failSwapOn: false
      authentication:
        anonymous:
          enabled: false
        webhook:
          enabled: true
        x509:
          clientCAFile: "/etc/kubernetes/pki/ca.crt"
      authorization:
        mode: Webhook
      clusterDomain: "cluster.local"
      clusterDNS:
      - "172.17.0.10"
      runtimeCgroups: "/system.slice/containerd.service"
      cgroupRoot: "/"
      cgroupsPerQOS: true
      EOF
  
  # Set kubelet configuration
  - sed -i "s|KUBELET_CONFIG_ARGS=.*|KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml|g" /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  
  # Start kubelet
  - systemctl start kubelet
  
  # Fun completion message
  - echo "🎉 Kubernetes Worker Node CloudInit completed! 🎉"
  - echo "📋 Next steps:"
  - echo "   1. Wait for control plane to be ready"
  - echo "   2. Get join command from control plane"
  - echo "   3. Run kubeadm join command"
  - echo "   4. Verify node is ready"
