apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vaultsecrets.vault.io
  labels:
    app.kubernetes.io/name: vault-operator
    app.kubernetes.io/part-of: database-ci
spec:
  group: vault.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              vault:
                type: object
                properties:
                  address:
                    type: string
                  namespace:
                    type: string
                  authMethod:
                    type: string
                    enum: ["token", "kubernetes", "aws", "azure", "gcp"]
                    default: "token"
                  tokenPath:
                    type: string
                  awsAuth:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: false
                      role:
                        type: string
                      region:
                        type: string
              ssm:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: true
                  region:
                    type: string
                  parameterStore:
                    type: object
                    properties:
                      vaultToken:
                        type: string
                      vaultConfig:
                        type: string
                      awsCredentials:
                        type: string
                      ansibleVaultPassword:
                        type: string
                      customSecrets:
                        type: array
                        items:
                          type: object
                          properties:
                            path:
                              type: string
                            key:
                              type: string
                  parameterStoreConfig:
                    type: object
                    properties:
                      refreshInterval:
                        type: string
                        default: "5m"
                      withDecryption:
                        type: boolean
                        default: true
                      filters:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            values:
                              type: array
                              items:
                                type: string
              aws:
                type: object
                properties:
                  region:
                    type: string
                  credentials:
                    type: object
                    properties:
                      secretName:
                        type: string
                      secretKey:
                        type: string
                  iamRole:
                    type: string
              git:
                type: object
                properties:
                  repository:
                    type: string
                  branch:
                    type: string
                    default: "main"
                  path:
                    type: string
                  credentials:
                    type: object
                    properties:
                      secretName:
                        type: string
                      secretKey:
                        type: string
              environment:
                type: string
                default: "dev"
              logLevel:
                type: string
                enum: ["debug", "info", "warn", "error"]
                default: "info"
              debug:
                type: boolean
                default: false
              features:
                type: object
                properties:
                  secretRotation:
                    type: boolean
                    default: true
                  secretSync:
                    type: boolean
                    default: true
                  auditLogging:
                    type: boolean
                    default: true
                  metrics:
                    type: boolean
                    default: true
              secrets:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    path:
                      type: string
                    keys:
                      type: array
                      items:
                        type: string
                    targetSecret:
                      type: string
                    targetNamespace:
                      type: string
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Running", "Succeeded", "Failed"]
              lastSync:
                type: string
                format: date-time
              lastError:
                type: string
              vaultVersion:
                type: string
              connectedSecrets:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    path:
                      type: string
                    lastUpdated:
                      type: string
                      format: date-time
                    status:
                      type: string
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: vaultsecrets
    singular: vaultsecret
    kind: VaultSecret
    shortNames:
    - vs
    - vault
