# Auto-generated Ansible Inventory for ${environment} environment
# Generated by Terraform on ${timestamp}

all:
  vars:
    environment: ${environment}
    aws_region: ${aws_region}
    vpc_id: ${vpc_id}
    vpc_cidr: ${vpc_cidr}

  children:
    ${environment}:
      vars:
        # Networking
        public_subnet_ids: ${jsonencode(public_subnet_ids)}
        private_subnet_ids: ${jsonencode(private_subnet_ids)}
        
        # Database
        rds_endpoint: ${rds_endpoint}
        rds_port: ${rds_port}
        rds_database: ${rds_database}
        rds_username: ${rds_username}
        
        # Compute
        tailscale_router_ip: ${tailscale_router_ip}
        
        # Security Groups
        web_sg_id: ${web_sg_id}
        db_sg_id: ${db_sg_id}
        
        # Kubernetes
        k8s_namespace: ${environment}
        
      hosts:
%{ for idx, ip in ec2_private_ips ~}
        ec2-${environment}-${idx}:
          ansible_host: ${ip}
          instance_id: ${ec2_instance_ids[idx]}
          ansible_user: ec2-user
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
%{ endfor ~}

