# Ansible inventory for operator
# This file is generated by Terraform and used by the Ansible operator pod

all:
  children:
    kubernetes:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: python3
      vars:
        environment: "${environment}"
        ansible_user: root
        
    aws_instances:
      hosts: {}
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        ansible_user: ubuntu
        environment: "${environment}"
        
  vars:
    # Global variables
    environment: "${environment}"
    project_name: "database-ci"
    operator_name: "ansible-operator"
