# Terraform configuration for operator
# This file is generated by Terraform and used by the Terraform operator pod

terraform {
  required_version = ">= 1.0"
  
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.0"
    }
  }

  backend "s3" {
    bucket         = "${state_bucket}"
    key            = "terraform-operator/${environment}/terraform.tfstate"
    region         = "${aws_region}"
    dynamodb_table = "${state_table}"
    encrypt        = true
  }
}

provider "aws" {
  region = "${aws_region}"
  
  default_tags {
    tags = {
      Environment = "${environment}"
      ManagedBy   = "terraform-operator"
      Project     = "database-ci"
    }
  }
}

provider "kubernetes" {
  # Uses in-cluster config when running in pod
  config_path = null
}

# Example resources that the operator can manage
resource "aws_s3_bucket" "operator_bucket" {
  bucket = "terraform-operator-${environment}-${random_id.bucket_suffix.hex}"
}

resource "random_id" "bucket_suffix" {
  byte_length = 4
}

resource "aws_s3_bucket_versioning" "operator_bucket_versioning" {
  bucket = aws_s3_bucket.operator_bucket.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "operator_bucket_encryption" {
  bucket = aws_s3_bucket.operator_bucket.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}
