# Terraform variables for operator
# This file is generated by Terraform and used by the Terraform operator pod

environment = "${environment}"
aws_region  = "${aws_region}"

# Example variables
project_name = "database-ci"
operator_name = "terraform-operator"
