name: Secure CI/CD Pipeline

on:
  push:
    branches: [main, working_branch]
    paths:
      - 'infrastructure/terraform/environments/dev/**'  # Auto-deploy dev
  pull_request:
    branches: [main, working_branch]
  workflow_dispatch: {}

env:
  AWS_REGION: us-east-1
  TERRAFORM_VERSION: "1.6.0"
  ANSIBLE_VERSION: "7.0.0"

# OIDC permissions for AWS federation
permissions:
  id-token: write
  contents: read

jobs:
  # deploy-dev:
  #   if: contains(github.event.head_commit.modified, 'environments/dev')
  #   environment: dev  # GitHub environment with secrets
    
  # deploy-test:
  #   if: contains(github.event.head_commit.modified, 'environments/test')
  #   environment: test
  #   needs: [deploy-dev]  # Only after dev succeeds

  # Security: Code Quality and Linting
  security-scan:
    name: Security & Code Quality
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for security analysis
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install pipenv
      run: |
        pip install pipenv
    
    - name: Install development tools
      run: |
        # Install packages directly to avoid Pipfile conversion issues
        pip install black==24.3.0 flake8==7.0.0 mypy==1.8.0 pytest==8.0.0
        pip install bandit==1.7.5 safety==3.0.1  # Security scanning
        pip install --pre -r requirements.txt  # Install from requirements.txt (--pre for ansible-core RC)
    
    - name: Code formatting check
      run: |
        black --check --diff hack || true
    
    - name: Linting
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Type checking
      run: |
        mypy . --ignore-missing-imports
    
    - name: Security scan with Bandit
      run: |
        bandit -r . -f json -o bandit-report.json || true
    
    - name: Dependency vulnerability scan
      run: |
        safety check --json --output safety-report.json || true
    
    - name: Upload security reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json

  # Infrastructure: Terraform Validation
  terraform-validate:
    name: Terraform Validation
    runs-on: ubuntu-latest
    environment: dev  # GitHub environment with the secret
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup OpenTofu
      run: |
        set -euo pipefail
        sudo apt-get update && sudo apt-get install -y wget unzip coreutils curl
        TOFU_VERSION="1.10.6"
        TOFU_FILE="tofu_${TOFU_VERSION}_linux_amd64.zip"
        TOFU_URL="https://github.com/opentofu/opentofu/releases/download/v${TOFU_VERSION}/${TOFU_FILE}"
        echo "Downloading ${TOFU_FILE} ..."
        wget -q "${TOFU_URL}"
        echo "Verifying SHA256 checksum..."
        SHA_URL_1="https://github.com/opentofu/opentofu/releases/download/v${TOFU_VERSION}/tofu_${TOFU_VERSION}_SHA256SUMS"
        SHA_URL_2="https://github.com/opentofu/opentofu/releases/download/v${TOFU_VERSION}/SHA256SUMS"
        SHA_URL_3="https://github.com/opentofu/opentofu/releases/download/v${TOFU_VERSION}/checksums.txt"
        CHECKSUMS=$(curl -fsSL "${SHA_URL_1}" || curl -fsSL "${SHA_URL_2}" || curl -fsSL "${SHA_URL_3}")
        if [ -z "${CHECKSUMS}" ]; then
          echo "Failed to download checksum list for OpenTofu v${TOFU_VERSION}" >&2
          exit 1
        fi
        EXPECTED_SHA=$(echo "${CHECKSUMS}" | grep "${TOFU_FILE}$" | awk '{print $1}')
        if [ -z "${EXPECTED_SHA}" ]; then
          echo "Failed to find expected SHA for ${TOFU_FILE}" >&2
          exit 1
        fi
        ACTUAL_SHA=$(sha256sum "${TOFU_FILE}" | awk '{print $1}')
        if [ "${EXPECTED_SHA}" != "${ACTUAL_SHA}" ]; then
          echo "SHA256 mismatch for ${TOFU_FILE}" >&2
          echo "Expected: ${EXPECTED_SHA}" >&2
          echo "Actual:   ${ACTUAL_SHA}" >&2
          exit 1
        fi
        echo "Checksum OK"
        unzip -o -q "${TOFU_FILE}"  # -o to overwrite without prompting
        sudo mv tofu /usr/local/bin/
        sudo chmod +x /usr/local/bin/tofu
        sudo ln -sf /usr/local/bin/tofu /usr/local/bin/terraform
        terraform version
    
    - name: Terraform Format Check
      run: terraform fmt -check -recursive
    
    - name: Terraform Init
      working-directory: infrastructure/terraform/environments/test
      run: |
        set -e
        echo "Initializing Terraform providers..."
        terraform init -backend=false -input=false -upgrade -reconfigure
        echo "Terraform init completed"
        if [ ! -d ".terraform/providers" ]; then
          echo "ERROR: .terraform/providers directory not found after init!"
          exit 1
        fi
    
    - name: Terraform Validate
      working-directory: infrastructure/terraform/environments/test
      run: |
        set -e
        # Ensure providers are initialized - reinit if needed
        if [ ! -d ".terraform/providers" ] || [ -z "$(ls -A .terraform/providers 2>/dev/null)" ]; then
          echo "Providers not found, reinitializing..."
          terraform init -backend=false -input=false -upgrade -reconfigure
        fi
        echo "Running terraform validate..."
        terraform validate

    - name: Verify AWS identity
      run: |
        echo "AWS identity:"
        aws sts get-caller-identity
    
    - name: Debug - Check secret availability
      run: |
        echo "Checking if AWS_ROLE_TO_ASSUME secret is available..."
        if [ -z "${{ secrets.AWS_ROLE_TO_ASSUME }}" ]; then
          echo "❌ AWS_ROLE_TO_ASSUME is EMPTY or NOT SET"
        else
          echo "✅ AWS_ROLE_TO_ASSUME is set"
          echo "Value length: ${#AWS_ROLE_TO_ASSUME}"
        fi
      env:
        AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
    
    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: github-actions-${{ github.run_id }}
        aws-region: ${{ env.AWS_REGION || 'us-east-1' }}

    - name: Verify AWS OIDC Provider identity
      run: |
        echo "AWS identity:"
        aws sts get-caller-identity

    - name: Terraform Plan (Dry Run)
      working-directory: infrastructure/terraform/environments/test
      run: |
        set -e
        # For local backend: -reconfigure is safe and ensures clean state
        # For S3/DynamoDB backend: can omit -reconfigure if backend config is stable
        terraform init -input=false -reconfigure
        terraform workspace select test || terraform workspace new test
        if [ -f "terraform.tfvars" ]; then
          terraform plan -var-file="terraform.tfvars" -out=tfplan
        else
          echo "Warning: terraform.tfvars not found, running plan without var file"
          terraform plan -out=tfplan
        fi
      # Credentials provided by OIDC session above

  # Configuration: Ansible Validation
  ansible-validate:
    name: Ansible Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Ansible and dependencies
      run: |
        pip install ansible==10.1.0
        pip install ansible-lint==24.12.2
        if [ -f "ansible/requirements.txt" ]; then
          pip install -r ansible/requirements.txt
        fi
    
    - name: Ansible Lint
      continue-on-error: true
      run: |
        if [ -d "ansible" ]; then
          ansible-lint ansible/ || echo "Ansible lint found issues (non-blocking)"
        elif [ -d "infrastructure/ansible" ]; then
          ansible-lint infrastructure/ansible/ || echo "Ansible lint found issues (non-blocking)"
        else
          echo "No Ansible directory found; skipping ansible-lint"
        fi
    
    - name: Ansible Syntax Check
      run: |
        if [ -d "ansible" ]; then
          find ansible/ -name "*.yml" -exec ansible-playbook --syntax-check {} \;
        elif [ -d "infrastructure/ansible" ]; then
          find infrastructure/ansible/ -name "*.yml" -exec ansible-playbook --syntax-check {} \;
        else
          echo "No Ansible directory found; skipping syntax check"
        fi

  # Security: SELinux Policy Validation
  selinux-validate:
    name: SELinux Policy Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install SELinux tools
      run: |
        sudo apt-get update
        sudo apt-get install -y selinux-policy-dev checkpolicy
    
    - name: Validate SELinux policies
      run: |
        cd ./infrastructure/ansible/files/selinux
        for policy in *.te; do
          echo "Validating $policy"
          checkmodule -M -m -o ${policy%.te}.mod $policy
        done

  # Deployment: ArgoCD Integration (if enabled)
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [security-scan, terraform-validate, ansible-validate, selinux-validate]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to ArgoCD
      run: |
        echo "Triggering ArgoCD deployment..."
        # ArgoCD will handle the actual deployment
        # This step would typically trigger ArgoCD sync
        curl -X POST "${{ secrets.ARGOCD_WEBHOOK_URL }}" \
          -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"ref": "main"}'

  # Security: Compliance Check
  compliance-check:
    name: Compliance & Security Standards
    runs-on: ubuntu-latest
    needs: [security-scan]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download security reports
      uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: security-reports
        if-no-artifact-found: warn
    
    - name: Compliance validation
      continue-on-error: true
      run: |
        echo "Checking compliance standards..."
        
        # Directories to exclude from compliance scanning
        EXCLUDES=(
          "--exclude-dir=.git"
          "--exclude-dir=.direnv"
          "--exclude-dir=demo-venv"
          "--exclude-dir=infrastructure/terraform/old-terraform-files"
          "--exclude-dir=docs"
        )

        # Tighter secret heuristic: flag only literal assignments like key: "value" or key = "value"
        # Ignore variable references (${...}), SSM paths, and known placeholders/examples
        SECRET_RC=0
        GREP_SECRET='(?i)(password|secret|api[_-]?key)\s*[:=]\s*"[^
        ]+"'
        if command -v rg >/dev/null 2>&1; then
          rg -n --pcre2 "$GREP_SECRET" \
            -g '!**/demo-venv/**' -g '!**/.direnv/**' -g '!**/.git/**' -g '!docs/**' -g '!infrastructure/terraform/old-terraform-files/**' \
            -g '*.tf' -g '*.yml' -g '*.yaml' \
            | rg -v 'example|placeholder|\$\{|ssm|parameter' || SECRET_RC=$?
          [ $SECRET_RC -eq 1 ] && SECRET_RC=0  # no matches → success
        else
          # fallback to grep
          grep -RInE "$GREP_SECRET" "${EXCLUDES[@]}" --include='*.tf' --include='*.yml' --include='*.yaml' . \
            | grep -Ev 'example|placeholder|\$\{|ssm|parameter' || SECRET_RC=$?
          [ $SECRET_RC -eq 1 ] && SECRET_RC=0
        fi
        if [ $SECRET_RC -ne 0 ]; then
          echo "Potential hardcoded secrets detected (non-blocking). Review output above.";
        fi

        # Check for dangerous configurations (protocol -1), excluding deprecated/old files
        DANGER_RC=0
        if command -v rg >/dev/null 2>&1; then
          rg -n 'protocol\s*=\s*-1' -g '!infrastructure/terraform/old-terraform-files/**' -g '*.tf' || DANGER_RC=$?
          [ $DANGER_RC -eq 1 ] && DANGER_RC=0
        else
          grep -RIn "protocol.*-1" --include='*.tf' . "${EXCLUDES[@]}" || DANGER_RC=$?
          [ $DANGER_RC -eq 1 ] && DANGER_RC=0
        fi
        if [ $DANGER_RC -ne 0 ]; then
          echo "Potential dangerous protocol configuration found (non-blocking).";
        fi
        
        echo "Compliance check completed (non-blocking)"
